---
title: millis()
categories: [ "Functions" ]
subCategories: [ "Time" ]
---





= millis()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Regresa el número de milisegundos desde que la placa Arduino inició el programa actual. Este número se sobreescribirá (volverá a cero), desdués de aproximadamente 50 días.
[%hardbreaks]


[float]
=== Syntax
`time = millis()`


[float]
=== Parameters
Ninguno

[float]
=== Regresa
Number of milliseconds since the program started (unsigned long)
Número de milisegundos desde que el programa inició (sin declararse long)
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code reads the milllisecond since the Arduino board began.

[source,arduino]
----
unsigned long time;

void setup(){
  Serial.begin(9600);
}
void loop(){
  Serial.print("Time: ");
  time = millis();

  Serial.println(time);    //prints time since program started
  delay(1000);             // wait a second so as not to send massive amounts of data
}
----
[%hardbreaks]

[float]
=== Notes and Warnings
Please note that the return value for millis() is an unsigned long, logic errors may occur if a programmer tries to do arithmetic with smaller data types such as int's. Even signed long may encounter errors as its maximum value is half that of its unsigned counterpart.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/BlinkWithoutDelay[Blink Without Delay]

--
// SEE ALSO SECTION ENDS
